// frontend/src/constants/flavorText.ts
//
// ==================================================================
//  DESIGN NOTE 944: THE VARIANT'S VOICE, KEYED TO THE OUTCOME
// ==================================================================
//
// SUPPLIED VERBATIM and kept that way: this file is a payload, not a derivation. Nothing here is computed,
// nothing is interpolated, and the only reason to edit it is to change what the game says.
//
// WHY IT IS KEYED BY OUTCOME RATHER THAN BY DIE FACE, in the author's own words: "Because your base-10
// rounding logic occasionally swallows a 10% modifier and returns the payout to 100%, we cannot map the
// flavor text strictly to the raw die face. We must map it to the effective outcome."
//
// WHICH IS THE SAME PREDICATE #938 ALREADY OWNS. `revenueOutcome` asks whether the FINAL rounded payout
// differs from the printed figure, not whether the die rolled something other than 100 -- a $50 turn at 90%
// pays $45, rounds back to $50, and must read as an ordinary day. The selector in `gameVariants` asks that
// function; this file only supplies the words.
//
// ==================================================================
//  DESIGN NOTE 950: ONE TENSE, BECAUSE THEY SHARE A LINE WITH A RESULT
// ==================================================================
//
// ASKED: "in your example, 'B&O ran for $170' the flavor text is written in present tense, the others are in
// past tense. Is this present tense true of all the revenue unchanged flavor text sentences?"
//
// IT WAS TRUE OF ALL TWENTY. Every `unchanged` line was present tense -- "The trains run, the fares are
// collected" -- while all 100 lines in the four modifier buckets were past. The mismatch was invisible while
// the buckets were read in isolation and became obvious the moment #949 put each line directly after
// "[Corp] ran for $X.", which is past tense and is the sentence they now have to agree with.
//
// SO THE TWENTY MOVED, and the other hundred were not touched. Verified by diff rather than by eye: the four
// modifier buckets are byte-identical across this edit.
//
// TWO OUTLIERS SURVIVE IN THE OTHER BUCKETS and are deliberately left alone, because they are supplied copy
// and were not what was asked about:
//   criticalBonus -- "The executives are already discussing monuments to themselves."
//   criticalMalus -- "An alarming number of passengers appear to have boarded without purchasing tickets."
// Both read as a present consequence of a past event, which is defensible; both are also the only two of
// their hundred that do it. Flagged rather than edited.
//
// NOT EVERY PRESENT-TENSE VERB IS A MISMATCH, which is why this was not done with a regex. "The accountants
// discovered that optimism is not legal tender" is a past main clause with a present subordinate, and that
// is correct English -- a general truth stays present. A sweep for present-tense verbs flags ten such lines
// and every one of them is right as written.
//
// THE ARRAY LENGTHS ARE LOAD-BEARING. The index rules are `seed % 20` for `unchanged` and `seed % 25` for the
// other four, so a short array would index past its end and put `undefined` into the Activity Log. There is a
// case in `flavorText.test.ts` asserting each length, because a dropped comma during an edit is silent here
// and loud three screens away.

export const UNPREDICTABLE_REVENUE_FLAVOR = {
  criticalMalus: [
    "The day's revenue took an unexpected excursion through the countryside.",
    "The accountants discovered a thrilling new category of expense.",
    "An alarming number of passengers appear to have boarded without purchasing tickets.",
    "The company’s profits were misplaced somewhere between here and Cincinnati.",
    "Train robbers made an unscheduled withdrawal from the company treasury.",
    "The books balanced beautifully, provided nobody actually looked at them.",
    "Management blamed the weather, and the weather declined to comment.",
    "The treasurer recommended everyone remain calm and stop asking questions.",
    "The railroad had a banner day, though unfortunately the banner was on fire.",
    "Train robbers demonstrated the practical dangers of carrying money by rail.",
    "A mysterious, catastrophic leak was discovered in the company’s coffers.",
    "An ambitious fare collector abruptly discovered the limits of optimism.",
    "The boiler pressure gauge turned out to be purely decorative.",
    "The local telegraph operator translated the timetable into Morse code backward.",
    "An entire herd of stubbornly stationary cattle occupied the mainline.",
    "A mid-level clerk quietly embezzled the month's coal budget.",
    "The Pinkertons demanded double pay just to keep the tracks clear of bandits.",
    "A sudden cholera outbreak led to the immediate quarantine of the terminal.",
    "Local farmers tore up the rails to protest the noise of the engines.",
    "A poorly timed bridge collapse sent three freight cars directly into the river.",
    "Someone intentionally greased the rails on the steepest grade in the mountains.",
    "The state legislature suddenly remembered to collect the regional railway tax.",
    "Train robbers relieved the company of 20% of its revenue.",
    "A patent dispute resulted in the federal seizure of the driving wheels.",
    "The train arrived perfectly on time, though unfortunately, the money did not.",
    "A bridge collapsed just before the train reached it.",
    "A landslide buried half the company’s track.",
    "A boiler exploded and sent the passengers scrambling.",
    "A plague scare emptied the stations.",
    "A rival railway lured away a shocking number of passengers.",
    "A flash flood washed away a section of track and the day’s profits.",
    "A strike brought the railway to an expensive standstill.",
    "A locomotive broke down at the worst possible moment.",
    "A shipment of valuable freight vanished somewhere along the line.",
    "A disgruntled engineer refused to move until his demands were met.",
    "A fire consumed a company depot and much of its contents.",
    "A herd of cattle occupied the tracks for most of the afternoon.",
    "A particularly ambitious competitor undercut the company’s fares.",
    "A severe storm disrupted nearly every scheduled departure.",
    "A shipment of coal arrived damp, useless, and expensive.",
    "A train was delayed so long that several passengers demanded their money back.",
    "A fraudulent ticket scheme cost the company a considerable sum.",
    "An inspector discovered enough violations to ruin everyone’s afternoon.",
    "A notorious train robber held up the company’s best-paying express.",
    "A man claiming to be a time traveler held up the train and demanded future currency.",
    "A mysterious gentleman boarded the train, predicted disaster, and proved correct.",
    "A damsel was found tied to the tracks, delaying the entire service.",
    "A runaway locomotive caused considerable confusion and considerably greater expense.",
    "A shipment of valuable goods was delivered to the wrong city.",
    "A flock of sheep brought the railway to an unexpectedly expensive halt.",
    "A competitor undercut the company’s fares and stole away its passengers.",
    "A severe storm damaged signals across the line.",
    "A shortage of locomotives forced the company to cancel several trains.",
    "A tunnel roof collapsed and blocked the line for hours.",
    "A winter freeze burst several miles of track.",
    "A shipment of perishable goods spoiled before reaching its destination.",
    "A reckless engineer ignored a signal and caused a costly collision.",
    "A government inspection closed a troublesome stretch of track.",
    "A band of escaped circus animals delayed the express and scattered the passengers.",
    "Several passengers began chanting “Cthulhu fhtagn,” and the train was subsequently delayed.",
    "A strange man made the passengers uncomfortable by asking whether they had seen a yellow sign.",
    "A trestle gave way beneath an empty freight car, closing the line for repairs.",
    "A locomotive’s firebox failed and left the express stranded in the countryside.",
    "A river rose high enough to flood the company’s principal depot.",
    "A shipment of livestock escaped during loading and caused a costly delay.",
    "A defective batch of rails forced the company to tear up and replace a newly laid section.",
    "A fire in a passenger carriage destroyed baggage and frightened away the evening travelers.",
    "A shortage of skilled engineers left several locomotives idle.",
    "A major freight customer switched to canal transport and took its business with it.",
    "A collision at the junction damaged two locomotives and disrupted the timetable.",
    "A bank failure left several of the company’s customers unable to pay their accounts.",
    "A violent hailstorm shattered carriage windows and sent passengers home.",
    "A shipment of machinery arrived damaged beyond repair.",
    "A disgruntled contractor abandoned a crucial construction project halfway through.",
    "A prolonged drought left the company’s water supplies dangerously low.",
    "A burst water main flooded the company’s busiest station.",
    "A newspaper published a sensational account of conditions aboard the railway.",
    "A pack of wolves scattered a valuable shipment of livestock before it reached market.",
    "A locomotive’s wheels slipped on an icy grade and damaged the track behind it.",
    "A mysterious fire destroyed the company’s records before the accountants could finish their work.",
    "A washed-out trestle halted three trains for the better part of a week.",
    "The company’s chief engineer absconded to a rival line with the survey maps.",
    "A boiler explosion on the mainline spooked passengers for a month.",
    "Striking coal miners cut off fuel supply to the yard.",
    "A rival line quietly bribed the local newspaper into printing safety scares.",
    "Locusts descended on the grain fields along the route, gutting freight receipts.",
    "The company treasurer was caught skimming and fled to Canada.",
    "A blizzard buried the mountain pass for eleven straight days.",
    "Investors panic-sold after a rumor (false) of insolvency.",
    "A rail spur collapsed under an overloaded livestock car.",
    "The board approved a disastrous fare-cutting war with a competitor.",
    "Termites were discovered in half the wooden trestles.",
    "A cholera outbreak in the terminal city emptied the passenger cars.",
    "The company’s only qualified brakeman quit to become a preacher.",
    "A flood swept away two miles of freshly laid track.",
    "Local farmers blocked the right-of-way in a land dispute.",
    "An overzealous state inspector shut down operations for “irregularities.”",
    "The paymaster lost the payroll satchel in a card game.",
    "A runaway freight car derailed in the switching yard, snarling traffic for days.",
    "Newspapers reported (accurately, this time) shoddy construction on the bridge.",
    "The company’s insurance underwriter cancelled coverage mid-season.",
    "A saboteur, never identified, loosened a critical rail joint.",
    "Drought dried up the water towers, stranding steam locomotives.",
    "The board wasted a fortune on a lavish but pointless inaugural ceremony.",
    "A competing line poached the entire station agent staff overnight.",
    "A locomotive struck a fallen tree and derailed.",
    "A sudden rockslide buried a freight convoy.",
    "A warehouse roof collapsed beneath the weight of a winter snow.",
    "A boiler’s safety valve failed and filled the platform with steam.",
    "A drunken engineer took the express down the wrong line and into a siding.",
    "A swarm of angry bees drove the passengers from the station.",
    "A great wave of river ice smashed into the company’s riverside facilities.",
    "A mob of striking workers seized the company’s locomotives.",
    "A shipment of dynamite was discovered to have been loaded beside the coal.",
    "A mysterious man appeared at the station and announced that the railway had awakened something beneath the earth."
  ],
  minorMalus: [
    "The accountants finally discovered that optimism is not legal tender.",
    "A few fares evaporated somewhere between the station and the ledger.",
    "Ten percent of the revenue inexplicably went to a better-paying railway.",
    "The conductor reported unusually generous interpretations of 'free travel'.",
    "A handful of pennies mysteriously acquired the status of 'operating expenses'.",
    "The ticket office had a surprisingly successful day selling fares at the wrong price.",
    "The treasurer rounded several figures in a direction most favorable to himself.",
    "The railway’s earnings had to be trimmed for excessive enthusiasm.",
    "Wall Street was firmly advised that 90% is still a very respectable number.",
    "The revenue arrived 10% late and was therefore charged a penalty.",
    "The company lost a little money and gained considerable experience.",
    "A modest revenue decline was blamed entirely on 'market conditions'.",
    "A minor catastrophe was quietly downgraded to an 'adjustment'.",
    "A flock of sheep absolutely refused to yield the right-of-way.",
    "The dining car ran out of whiskey before noon, enraging the first-class travelers.",
    "The local alderman held up the train for a prolonged ribbon-cutting ceremony.",
    "The conductor mislaid his pocket watch and ran the route purely on intuition.",
    "The train was delayed by a slow-moving circus parade crossing the tracks in town.",
    "The coal tender caught fire, but only a little bit.",
    "A rogue spark set a wealthy passenger's bespoke hat ablaze.",
    "Local pranksters replaced the signal lanterns with red glass.",
    "A sudden downpour caused a brief flash flood over the tracks.",
    "The local water tower was accidentally drained by thirsty locals.",
    "An eccentric tycoon demanded an unscheduled stop to look at a nice tree.",
    "The trains ran splendidly, though the finances ran somewhat less so.",
    "A few passengers claimed they had already paid their fares.",
    "A conductor discovered that his ticket punch had gone missing.",
    "Several passengers talked their way into reduced fares.",
    "A minor delay prompted an irritating number of refunds.",
    "A cow wandered onto the tracks and delayed one departure.",
    "A shipment arrived late and cost the company a few customers.",
    "The ticket office accidentally sold several tickets twice.",
    "A clerk misplaced a small but important stack of receipts.",
    "A handful of passengers decided to ride in the wrong class.",
    "A minor mechanical failure delayed the morning train.",
    "Several crates of freight were loaded onto the wrong train.",
    "An overzealous conductor accidentally waived a few fares.",
    "A rainstorm discouraged some less determined travelers.",
    "A suspicious number of passengers claimed to be railway employees.",
    "The company paid a small fortune to replace a broken signal.",
    "A stationmaster discovered that someone had borrowed the company’s horse.",
    "A few passengers missed their train and demanded compensation anyway.",
    "A shipment of coal arrived with rather more rocks than coal.",
    "An argument over fares delayed the afternoon service.",
    "A porter dropped several parcels into an inconvenient puddle.",
    "A poorly timed sneeze caused a brief commotion at the ticket office.",
    "A newspaper printed an unfavorable rumor about the company.",
    "A gentleman boarded the train without his wallet and considerable confidence.",
    "A stray dog occupied the first-class carriage until persuaded otherwise.",
    "The treasurer discovered that someone had been rounding down.",
    "A broken coupling delayed one of the afternoon trains.",
    "A misplaced timetable sent several passengers to the wrong platform.",
    "A shortage of porters slowed the morning departures.",
    "A stubborn mule refused to clear the tracks.",
    "A faulty signal caused a brief delay at the junction.",
    "A rooster escaped from a crate and spent the journey in first class.",
    "A passenger insisted that the locomotive had insulted him.",
    "A small dog boarded the train and refused to reveal its destination.",
    "A traveling salesman accidentally demonstrated his product to the conductor instead of his customers.",
    "A gentleman brought a goat aboard and claimed it had purchased a ticket.",
    "A loose horseshoe delayed the departure while the station staff searched for its owner.",
    "A baggage clerk attached the wrong labels to several trunks.",
    "A passenger spilled coffee over an important timetable.",
    "A rain leak spoiled a few sacks of grain in the freight shed.",
    "A locomotive needed an unexpected chimney cleaning before departure.",
    "A horse-drawn wagon blocked the station entrance during the busiest hour.",
    "A porter accidentally loaded a passenger’s trunk into the wrong carriage.",
    "A cracked window required a last-minute repair before the train could leave.",
    "A minor shortage of firewood slowed one locomotive.",
    "A passenger boarded the wrong train and demanded that the railway correct his mistake.",
    "A flock of chickens escaped from a freight crate and disrupted loading.",
    "A station cat occupied the telegraph desk until forcibly removed.",
    "A baggage porter mislaid a gentleman’s hat and received a stern lecture.",
    "A faulty whistle caused the engineer to miss a station signal.",
    "A muddy road discouraged several would-be passengers from reaching the station.",
    "A merchant disputed the weight of his freight and refused to settle the bill promptly.",
    "A stack of newspapers was delivered to the wrong station.",
    "A passenger’s oversized trunk occupied an unreasonable amount of carriage space.",
    "A small spark scorched part of a freight wagon before being extinguished.",
    "A station clerk spent half the morning correcting an error in the passenger register.",
    "A minor axle fault took one locomotive out of service for repairs.",
    "Fog delayed the morning schedule by several hours.",
    "A dispute over freight rates with a connecting line trimmed receipts.",
    "The company underprinted tickets and had to turn away late passengers.",
    "A wheel bearing seized on the express run.",
    "Local livestock wandered onto the tracks, causing repeated delays.",
    "A minor accounting error shorted the quarterly ledger.",
    "Rain-softened embankments slowed freight to half speed.",
    "The stationmaster overslept and delayed the morning departure.",
    "A shipment of lumber was damaged in transit and had to be discounted.",
    "Ticket agents struck briefly over uniform allowances.",
    "A telegraph line went down, causing scheduling confusion.",
    "One passenger car was pulled for unscheduled maintenance.",
    "A minor coupling failure separated a freight train mid-route.",
    "The company lost a small freight contract to a cheaper competitor.",
    "Muddy roads kept wagon traffic from reaching the depot on time.",
    "A clerical mix-up double-booked cargo space.",
    "Squabbling shareholders delayed an important routing decision.",
    "A brief coal shortage forced reduced service for two days.",
    "The conductor misplaced the day’s fare receipts (later found).",
    "A minor bridge repair closed one track temporarily.",
    "Unseasonable heat warped a short stretch of rail.",
    "A competing stagecoach line undercut fares on a parallel route.",
    "The company’s newest hire derailed a handcar in the yard (no injuries, much embarrassment).",
    "A late harvest meant fewer grain shipments than projected.",
    "A passenger’s luggage burst open on the platform.",
    "A flock of ducks wandered into the station concourse.",
    "A carriage axle began making an alarming noise.",
    "A passenger’s pocket watch fell between the platform boards.",
    "A sudden downpour caught the waiting passengers without umbrellas.",
    "A porter accidentally sent a trunk rolling down the platform.",
    "A telegraph operator received a message that made him sigh heavily.",
    "A gentleman’s top hat was carried away by a sudden gust.",
    "A passenger discovered that his ticket had been issued for yesterday.",
    "A station cat fell asleep on the timetable and refused to move."
  ],
  unchanged: [
    "Nothing unexpected happened. The accountants were suspicious.",
    "The railway enjoyed the rare luxury of normality.",
    "The trains ran, the fares were collected, and nobody got robbed.",
    "The day passed without financial incident.",
    "The market experienced neither joy nor despair.",
    "A train departed. A train arrived. Money changed hands.",
    "The railway successfully avoided both prosperity and disaster.",
    "The books closed without requiring any creative interpretation.",
    "The day’s receipts were neither miraculous nor catastrophic.",
    "Business was conducted with admirable mediocrity.",
    "No robbers, disasters, or miracles disturbed the day’s receipts.",
    "The accountants found the books pleasantly boring.",
    "The company achieved the remarkable feat of changing nothing.",
    "Management was pleased to announce absolutely nothing.",
    "The railway neither struck gold nor lost its shirt.",
    "The railway avoided excitement, which was excellent news for the accountants.",
    "Passengers paid their fares, and everyone behaved themselves.",
    "Nothing happened to the revenue. For once, this was good news.",
    "The railway’s earnings remained as steady as the track.",
    "The treasurer closed the ledger and got to go home early.",
    "The trains ran on schedule, more or less.",
    "The passengers traveled, the conductors collected fares, and nothing remarkable occurred.",
    "The day passed without incident or inspiration.",
    "The railway enjoyed an entirely ordinary day.",
    "The company encountered neither fortune nor misfortune.",
    "The trains ran, and the ledger remained pleasantly uneventful.",
    "The passengers behaved themselves, which was almost disappointing.",
    "No calamity interrupted the day’s business.",
    "No miracle improved the company’s fortunes, either.",
    "The railway continued along its accustomed course.",
    "The company’s fortunes remained exactly where they had been.",
    "The day produced no surprises worth entering in the ledger.",
    "The trains arrived, the passengers paid, and everyone went home.",
    "Business proceeded without excitement or financial consequence.",
    "The railway experienced a perfectly respectable amount of normality.",
    "The company’s books remained stubbornly unchanged.",
    "The directors found nothing worth celebrating or complaining about.",
    "The railway successfully completed another unremarkable day.",
    "Nothing unusual happened, which was unusual enough to mention.",
    "The company avoided both disaster and prosperity.",
    "The day’s business unfolded exactly as expected.",
    "The accountants found nothing interesting in the day’s receipts.",
    "The railway carried on without mishap, miracle, or monkey business.",
    "The company neither gained nor lost any particular distinction.",
    "The day ended precisely as uneventfully as it had begun.",
    "The railway enjoyed a perfectly ordinary day of commerce.",
    "The trains ran, the fares were collected, and nobody was robbed.",
    "The shareholders experienced neither joy nor despair.",
    "Business proceeded with admirable mediocrity.",
    "The directors were pleased to announce absolutely nothing.",
    "The treasury remained precisely as full as it had been before.",
    "Commerce proceeded at its usual, unremarkable pace.",
    "The directors declared the day “satisfactory” and adjourned for lunch.",
    "The company survived another day without making the newspapers.",
    "The treasurer found nothing interesting to report.",
    "The railway completed its runs with commendable dullness.",
    "The passengers reached their destinations without complaint.",
    "The conductors collected the usual fares and kept the trains moving.",
    "The company encountered an entirely average day.",
    "The railway carried its passengers and freight without incident.",
    "The stations remained busy enough to keep everyone occupied.",
    "The trains followed their schedules and nobody made a fuss.",
    "The railway completed another routine round of business.",
    "The day’s traffic proved neither exceptional nor disappointing.",
    "The company’s locomotives performed precisely as expected.",
    "The railway had precisely the sort of day nobody wrote about.",
    "The passengers came and went with admirable predictability.",
    "The railway passed the day without making history.",
    "The accountants recorded the day and promptly forgot it.",
    "A passenger spent the entire journey arguing with a hat.",
    "A gentleman claimed to have invented the railway, but nobody believed him.",
    "A mysterious goose followed the train from station to station.",
    "A passenger attempted to pay his fare with a remarkably convincing seashell.",
    "A local poet composed an ode to the company’s baggage cars.",
    "A gentleman boarded the train carrying a portrait of himself and nobody asked why.",
    "A passenger insisted that the moon was following the train and refused to elaborate.",
    "A conductor spent ten minutes searching for a missing hat that was on his head.",
    "A traveling lecturer gave an impromptu speech to an empty carriage.",
    "A man brought a ladder aboard the train and declined to explain its purpose.",
    "The morning’s departures and arrivals proceeded according to the timetable.",
    "The station staff completed their duties without noteworthy difficulty.",
    "The railway carried its customary mixture of travelers and merchandise.",
    "The engineers reported that the locomotives had performed satisfactorily.",
    "The company received no particularly good or bad news during the day.",
    "The passengers traveled in relative comfort and reached their destinations.",
    "The stationmaster recorded the day’s traffic and found nothing remarkable.",
    "The railway’s routine business continued without interruption.",
    "The telegraph delivered its messages without causing any particular excitement.",
    "The freight yards remained busy, but nothing extraordinary occurred.",
    "The company’s employees completed another day’s work without incident.",
    "The timetable survived the day without requiring revision.",
    "The railway encountered the usual assortment of delays, complaints, and paperwork.",
    "The trains ran well enough to keep everyone reasonably satisfied.",
    "The day’s business generated neither celebration nor recrimination.",
    "The company concluded its operations without finding cause for alarm.",
    "Trains ran on schedule, more or less as expected.",
    "Ordinary freight and passenger traffic moved, nothing remarkable.",
    "The line posted routine, unremarkable earnings this quarter.",
    "Weather was fair; operations proceeded without incident.",
    "The board met, approved the minutes, and adjourned.",
    "A new timetable was issued with only minor adjustments.",
    "Farmers shipped their usual seasonal produce.",
    "Maintenance crews completed scheduled track inspections.",
    "The mail contract was renewed under the same terms.",
    "A modest number of new settlers arrived via the line.",
    "Coal deliveries proceeded at the usual pace.",
    "Nothing of note appeared in this week’s ledger.",
    "The stationmaster reported “business as usual.”",
    "Ticket sales tracked closely with last month’s figures.",
    "A routine locomotive inspection turned up nothing unusual.",
    "Local merchants shipped their goods as expected.",
    "The company quietly paid its usual dividend.",
    "Passenger counts held steady with the season.",
    "A new conductor completed an uneventful first week.",
    "The line’s freight yard operated at typical capacity.",
    "Nothing was reported from the district superintendent.",
    "Trains arrived and departed within normal tolerances.",
    "The company’s books balanced without surprises.",
    "Livestock shipments matched seasonal averages.",
    "It was a quiet week, the calm before or after something else.",
    "A photographer took a portrait of the locomotive and its crew.",
    "A newspaper vendor announced the afternoon edition to the waiting passengers.",
    "A church procession crossed the square while the train waited.",
    "A military band marched past the station without stopping.",
    "A gentleman practiced his violin in an empty waiting room.",
    "A pair of newlyweds departed beneath a shower of rice.",
    "A traveling lecturer demonstrated a peculiar electrical apparatus.",
    "A child counted the wheels as the locomotive passed.",
    "A gentleman attempted to impress the passengers with a magic trick.",
    "A stray parrot repeated the stationmaster’s announcements."
  ],
  minorBonus: [
    "The railway finally discovered that people are willing to pay for this service.",
    "The railway accidentally made itself profitable.",
    "A fortunate combination of full trains and questionable accounting boosted receipts.",
    "Business was brisk, and nobody has yet asked why.",
    "Ticket sales exceeded expectations by a suspiciously convenient margin.",
    "Business was, as the treasurer announced, 'better than we have any right to expect'.",
    "The company discovered the ancient and powerful business strategy of charging money.",
    "Management congratulated itself on a plan it had absolutely nothing to do with.",
    "The increased receipts prompted immediate discussion of enormous executive salaries.",
    "A favorable wind blew directly into the corporate coffers.",
    "The company’s treasury enjoyed a modest but welcome expansion.",
    "The market discovered that optimism can, occasionally, be correct.",
    "Prosperity arrived promptly and without requiring a connecting train.",
    "A sudden local festival caused a massive surge in third-class ticket sales.",
    "A glorious tailwind across the plains saved half a ton of coal.",
    "The competing stagecoach company tragically broke an axle.",
    "The conductor somehow managed to cram forty extra people into the second-class car.",
    "A local bridge toll was unexpectedly suspended by the governor.",
    "The fireman discovered a vein of exceptionally high-grade anthracite.",
    "A rival company's train was delayed, sending all of their passengers to you.",
    "A mild winter kept the tracks perfectly clear of ice and snow.",
    "The dining car's new menu proved wildly popular with the socialites.",
    "Local merchants offered a bounty for the early delivery of their goods.",
    "An aggressive local advertising campaign actually worked for once.",
    "The trains were full, the fares were collected, and nobody lost the ledger.",
    "A popular excursion filled several otherwise empty carriages.",
    "A wealthy traveler chose the railway over a rival line.",
    "A shipment of freight arrived early and delighted its recipient.",
    "Several extra passengers purchased tickets at the last minute.",
    "A favorable newspaper article attracted a few curious travelers.",
    "A station fête brought an unexpected crowd to the platform.",
    "A rival railway suffered a delay and surrendered several passengers.",
    "A shipment of coal arrived early and saved the company a little money.",
    "A conductor collected several fares that had been overlooked earlier.",
    "A group of merchants discovered the convenience of rail travel.",
    "An unexpected delegation filled an entire carriage.",
    "A fashionable traveler gave the railway an unexpectedly glowing review.",
    "A local fair sent a welcome stream of passengers toward the stations.",
    "A competitor’s unpopular timetable sent several customers our way.",
    "A shipment of valuable goods fetched a better price than expected.",
    "A wealthy family chartered a carriage for an afternoon outing.",
    "Several passengers paid extra to avoid traveling with the commoners.",
    "A popular lecturer attracted a respectable crowd to the railway.",
    "A fortunate scheduling change filled a few empty seats.",
    "A merchant discovered that his goods traveled better by rail than by wagon.",
    "The company’s punctuality earned a little unexpected praise.",
    "A sudden spell of fine weather encouraged a few extra excursions.",
    "A station refreshment stand proved unexpectedly popular.",
    "Several travelers chose the company after hearing glowing reports from a neighbor.",
    "A fortunate coincidence filled the train and pleased the treasurer.",
    "The railway discovered that people were willing to pay for this service.",
    "Passenger traffic exceeded expectations by a modest margin.",
    "The company’s coffers enjoyed a welcome little boost.",
    "Business was brisk, and nobody had yet asked why.",
    "The conductor reported a gratifying abundance of paying customers.",
    "A favorable wind blew directly into the shareholders’ pockets.",
    "The ticket office enjoyed an unexpectedly productive afternoon.",
    "The railway accidentally made itself slightly more profitable.",
    "Receipts climbed steadily, to everyone’s mild delight.",
    "The books contained an unusually pleasant surprise.",
    "More passengers than usual elected to contribute to the company’s prosperity.",
    "The company’s finances received a modest injection of optimism.",
    "Revenue picked up a little steam.",
    "The railway enjoyed a small but welcome commercial boom.",
    "The trains were full, the fares were collected, and the ledger survived.",
    "The company’s financial outlook brightened somewhat.",
    "A respectable number of passengers brought respectable amounts of money.",
    "The railway earned a little extra and immediately took credit for it.",
    "A modest improvement in business left the treasurer smiling.",
    "The company’s receipts arrived slightly ahead of expectations.",
    "The railway caught a favorable current of commerce.",
    "A few extra coins found their way into the company coffers.",
    "The company’s fortunes improved just enough to buy lunch.",
    "The shareholders discovered that optimism could occasionally be correct.",
    "The railway finished the day a little richer and considerably smugger.",
    "A gentleman paid his fare twice rather than admit he had forgotten paying once.",
    "A local eccentric purchased tickets for his entire collection of pigeons.",
    "A passenger mistook the railway station for a hotel and paid before discovering his error.",
    "A traveling circus hired the railway to transport an unusually profitable elephant.",
    "A prosperous gentleman won a bet and spent the winnings on a railway excursion.",
    "An early harvest brought a surge of grain shipments.",
    "A local fair drew unexpected crowds to the depot.",
    "The company won a small but lucrative mail contract.",
    "Good weather allowed an extra freight run to squeeze in.",
    "A rival line’s derailment sent its stranded passengers your way.",
    "A new sawmill along the route boosted lumber traffic.",
    "The stationmaster’s clever scheduling squeezed in an extra express run.",
    "Word spread of the line’s punctuality, drawing new passengers.",
    "A traveling circus booked an entire freight car.",
    "Local merchants placed larger-than-usual orders ahead of the holidays.",
    "A modest gold strike nearby brought a wave of prospectors.",
    "The company negotiated a favorable new freight rate with a connecting line.",
    "Fine weather extended the shipping season by several weeks.",
    "A newspaper printed a glowing review of the line’s service.",
    "A regional cattle drive routed extra stock through the yard.",
    "The company’s new ticket agent proved unexpectedly good at upselling.",
    "A bumper cotton crop filled the freight cars.",
    "A state fair drew excursion travelers from neighboring towns.",
    "The line picked up overflow freight from a competitor’s breakdown.",
    "A well-timed rate cut drew business away from a rival.",
    "Improved timekeeping earned a bonus government mail stipend.",
    "A local factory opened and signed a shipping contract.",
    "Favorable river levels allowed smoother connections at the wharf.",
    "The company hosted a well-attended excursion to the coast.",
    "A visiting dignitary’s tour brought favorable press and new riders.",
    "A local orchestra drew an enthusiastic crowd to the station.",
    "A popular boxing match brought spectators from three neighboring towns.",
    "A celebrated author’s new book sent readers rushing to the bookseller.",
    "A wealthy family arranged an elaborate country excursion.",
    "A local brewery began sending its barrels by rail.",
    "A shipment of fine china arrived safely and impressed its purchaser.",
    "A traveling auctioneer filled the station with eager buyers.",
    "A famous racehorse was transported to town for an important event.",
    "A merchant discovered that the railway could deliver his goods before his competitors.",
    "A local inventor demonstrated a machine that attracted considerable attention."
  ],
  criticalBonus: [
    "The railway apparently discovered where all the money is.",
    "A glorious torrent of revenue flooded the company’s coffers.",
    "Passenger demand became briefly indistinguishable from panic.",
    "The treasurer checked the figures three times and liked them every time.",
    "The trains were packed, the fares were flowing, and the executives were insufferable.",
    "Revenue climbed like a locomotive with a downhill grade and no brakes.",
    "The company had its best day since someone invented the ticket.",
    "The railway enjoyed an almost suspicious degree of prosperity.",
    "Revenue exploded upward, prompting the treasurer to hide the good news from competitors.",
    "The company’s earnings entered the realm of the frankly ridiculous.",
    "The executives are already discussing monuments to themselves.",
    "Revenue arrived in such quantities that the accountants required a larger ledger.",
    "Business was booming, and management immediately took credit.",
    "The railroad struck financial gold without having to lay another mile of track.",
    "A sudden gold strike in the foothills caused an absolute passenger stampede.",
    "A competitor's bridge collapsed, giving the company a total monopoly for the week.",
    "A massive army deployment required every available flatcar at premium rates.",
    "A major industrialist decided to relocate his entire factory using the railway.",
    "The federal government decided to pay its freight debts in pure silver bullion.",
    "A tycoon bought every first-class ticket just to enjoy the silence.",
    "An unexpected World's Fair exhibit was routed exclusively through the network.",
    "Management successfully bribed the state legislature for a massive subsidy.",
    "A speculative land boom caused ticket prices to quadruple overnight.",
    "An incredibly wealthy eccentric rented the entire train for a private party.",
    "A fortunate alignment of the stars and the stock market essentially printed money.",
    "A grand exhibition sent crowds rushing toward the railway.",
    "A rival railway suffered a spectacular breakdown and lost its passengers to us.",
    "A wealthy industrialist chartered nearly an entire train.",
    "A sudden boom in trade filled every available freight car.",
    "A celebrated dignitary arrived and brought half the town to the station.",
    "A holiday crowd overwhelmed the ticket office and delighted the treasurer.",
    "A competing railway closed unexpectedly, sending its passengers our way.",
    "A gold shipment filled the freight cars and the company’s coffers.",
    "A fashionable society declared the railway the preferred means of travel.",
    "A record harvest produced a mountain of freight and a mountain of receipts.",
    "A wildly successful excursion filled every carriage twice over.",
    "A wealthy traveler paid handsomely to have the train delayed for his convenience.",
    "A rival company’s scandal made our railway suddenly fashionable.",
    "A government delegation chartered the finest train in the fleet.",
    "A booming market sent merchants and merchandise pouring onto the railway.",
    "A famous performer arrived by train and brought an enormous crowd with him.",
    "A new town opened along the line and immediately filled the trains.",
    "A spectacular fair turned the station into a sea of paying customers.",
    "A competitor’s unfortunate timetable made our railway the obvious choice.",
    "An exceptionally profitable freight contract fell unexpectedly into the company’s lap.",
    "A shipment of precious goods required nearly every available carriage.",
    "A mysterious benefactor purchased a staggering number of tickets for strangers.",
    "A fortune in freight arrived safely, promptly, and entirely at our expense.",
    "A man claiming to be from the future purchased every ticket to avoid changing history.",
    "A sudden rush of passengers left the company counting money until midnight.",
    "The railway apparently discovered where all the money was.",
    "The trains were packed, the fares were flowing, and the shareholders were insufferable.",
    "Every seat was occupied, every fare was collected, and every director was delighted.",
    "The coffers swelled to an alarming and deeply satisfying degree.",
    "Business boomed, and the directors immediately took credit.",
    "Passenger receipts surged past even the most extravagant projections.",
    "The railroad struck financial gold without laying another mile of track.",
    "A remarkable number of people decided that the railway was worth paying for.",
    "The shareholders were already discussing monuments to themselves.",
    "A wave of prosperity swept across the entire system.",
    "The railway suddenly became the envy of every company with fewer coins.",
    "The company’s financial fortunes acquired considerable steam.",
    "A spectacular day at the stations left the treasury groaning under the strain.",
    "The directors declared the result “entirely due to sound management.”",
    "The railway’s coffers overflowed, and modesty departed on the next train.",
    "Twenty percent more revenue arrived, and nobody questioned it.",
    "Prosperity arrived on schedule and brought several bags of money.",
    "A famous opera singer traveled by rail and somehow caused half the county to follow.",
    "A wealthy eccentric chartered the entire train so he could enjoy the scenery alone.",
    "A circus troupe paid handsomely to transport an elephant, three lions, and one very nervous accountant.",
    "A mysterious stranger arrived with a suitcase of gold and refused to explain where it came from.",
    "A man claiming to have returned from the future purchased every available ticket before disappearing at the next station.",
    "Several passengers began chanting “Cthulhu fhtagn,” and somehow every carriage filled immediately.",
    "A strange man proclaimed that the Yellow Sign had brought him to the railway, then purchased the entire first-class carriage.",
    "A mysterious traveler emerged from the fog carrying a bag of gold and asked for the fastest train west.",
    "A passenger claimed that an ancient power had awakened beneath the railway and was apparently very fond of first-class travel.",
    "A strange procession arrived at the station beneath a yellow banner and purchased every available ticket.",
    "A new industrial concern signed an exceptionally lucrative long-term freight agreement.",
    "A sudden population boom filled the towns along the company’s route with eager travelers.",
    "A wealthy investor financed an ambitious expansion and routed his own business through the railway.",
    "A record shipment of cotton overwhelmed the freight yards and enriched the company handsomely.",
    "A celebrated political convention brought thousands of visitors to the railway’s stations.",
    "A distant gold discovery sent a flood of prospectors westward aboard the company’s trains.",
    "A rival company’s locomotive shortage left its customers with no choice but to ride with us.",
    "A mysterious benefactor purchased an extraordinary number of tickets and asked that his identity remain secret.",
    "A gold rush along the route sent prospectors flooding to the depot.",
    "The line secured an exclusive, highly profitable mail contract.",
    "A rival line’s bankruptcy sent its customers flocking to your rails.",
    "An unusually bountiful harvest overwhelmed the freight yards with grain.",
    "The company completed a daring new bridge, opening a lucrative shortcut.",
    "A celebrity’s cross-country tour booked out an entire train.",
    "Word of a silver strike triggered a stampede of paying passengers.",
    "The line won a hotly contested government subsidy.",
    "A record cotton crop filled every available freight car.",
    "The company’s new express service became the talk of the region.",
    "A major industrial plant signed an exclusive shipping agreement.",
    "Investors poured capital in after a glowing report in the financial press.",
    "The line’s punctuality earned it the state’s official mail franchise.",
    "A dazzling grand-opening celebration drew travelers from three states.",
    "A bumper tobacco harvest sent warehouses scrambling for rail space.",
    "The company undercut and absorbed a struggling competitor’s routes.",
    "A world’s fair nearby sent attendance — and freight — through the roof.",
    "Favorable trade terms opened a lucrative new export route.",
    "The line’s directors negotiated a windfall land grant along the route.",
    "A newly discovered coal seam turned the line into a hauling powerhouse.",
    "A record cattle drive flooded the stockyards and filled every car.",
    "The company’s daring night-service gambit paid off spectacularly.",
    "A visiting head of state’s chartered train brought enormous prestige and fares.",
    "The line became the preferred route for a booming immigrant wave.",
    "An unexpected merger offer validated the line’s soaring value, and business boomed alongside it.",
    "A presidential candidate’s speaking tour filled the railway’s carriages for an entire week.",
    "A vast shipment of iron arrived just as a new factory began production.",
    "A spectacular theatrical production brought visitors from every town along the line.",
    "A celebrated foreign dignitary arrived with an entourage large enough to fill several trains.",
    "A devastating fire in a neighboring town sent merchants rushing to rebuild through the railway.",
    "A new invention was demonstrated to an enormous crowd, and everyone wanted to see it.",
    "A wealthy railroad speculator arrived with a trunk full of cash and an appetite for expansion.",
    "A mysterious benefactor paid for an entire trainload of passengers to travel west.",
    "A newly struck gold vein sent prospectors rushing toward the company’s western terminus.",
    "A massive government construction project required every available freight car."
  ]
};
