/**
 * @jest-environment node
 */
// frontend/src/utils/jx2aKmsSigningParity.test.ts
//
// ==================================================================
//  JX-2A: THE RELAYER'S KMS SIGNING PIPELINE, END TO END, WITH A DISPOSABLE LOCAL KEY -- EVERY RELAYER ROUTE
// ==================================================================
//
// What the relayer does for every escrow transaction (`server/src/escrow/juno/relayer.ts` `advance`), step by step, with
// the PRODUCTION modules and only the KMS call replaced:
//
//   escrow intent (RELAYER_EXECUTE.<route>)  ->  decideGas (the policy's gas limit and fee)
//   ->  prepareExecuteTx (MsgExecuteContract, TxBody, AuthInfo, SignDoc, SHA-256 digest)
//   ->  openKmsDigestSigner.sign (the KMS port: DER ECDSA over the DIGEST -> strict DER parse -> r||s -> low-s ->
//       verify-before-use under the key GetPublicKey reported)
//   ->  assembleTx (TxRaw, tx hash)
//
// and then, as the chain does, INDEPENDENTLY: the TxRaw is decoded with cosmjs-types, every field is read back, the
// SignDoc is rebuilt by @cosmjs/proto-signing from the DECODED bytes, and the signature is verified by @cosmjs/crypto AND
// by Node's OpenSSL over the sign bytes. Three implementations agree with the server's hand encoder.
//
// THE FAKE KMS is independent of the server's secp256k1 code: the key is generated by Node's OpenSSL (its SPKI export is
// what GetPublicKey answers), and Sign is `elliptic` over the 32-byte digest with a RANDOM personalisation (so the
// signature is NOT deterministic, as real KMS ECDSA is not) and canonical:false (so high-s answers occur; every other
// low-s answer is also returned as its high-s twin, so the normalisation path is certainly exercised). Its answer is
// minimal DER, as KMS answers.
//
// Nothing here reads a network, AWS or a file key: the key exists only in this process and is discarded. Nothing is
// broadcast. The only thing allowed to differ between two signings of the same transaction is the signature (and so the
// TxRaw bytes and the tx hash); the sign bytes may not.

import { createHash, createPublicKey, generateKeyPairSync, randomBytes, verify as opensslVerify, type KeyObject } from "crypto";
import { Secp256k1, Secp256k1Signature, sha256 } from "@cosmjs/crypto";
import { toBech32 } from "@cosmjs/encoding";
import { rawSecp256k1PubkeyToRawAddress, encodeSecp256k1Pubkey } from "@cosmjs/amino";
import { makeSignBytes, makeSignDoc, encodePubkey } from "@cosmjs/proto-signing";
import { TxRaw, TxBody, AuthInfo, Fee, SignerInfo } from "cosmjs-types/cosmos/tx/v1beta1/tx";
import { SignMode } from "cosmjs-types/cosmos/tx/signing/v1beta1/signing";
import { PubKey } from "cosmjs-types/cosmos/crypto/secp256k1/keys";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";

import { addressOfPublicKey, assembleTx, MSG_EXECUTE_CONTRACT_TYPE_URL, prepareExecuteTx, simulationTx, txHashOf } from "../../../server/src/escrow/juno/cosmosTx";
import { isLowS, publicKeyOf, signDigest, SECP256K1_N, bytesToBigInt, bigIntTo32 } from "../../../server/src/escrow/juno/secp256k1";
import { openKmsDigestSigner, SignerError, type KmsClient } from "../../../server/src/escrow/juno/signer";
import { ceilDiv, decideGas, DEFAULT_GAS_POLICY, type GasPolicy } from "../../../server/src/escrow/juno/gasPolicy";
import { RELAYER_EXECUTE } from "../../../server/src/escrow/juno/junoContract";
import { annulDigestV1, consentDigestV1 } from "../gameEngine/settlementPayload";
import vectors from "./__fixtures__/settlement/settlementPayloadVectorsV1.json";

/* The JX-2 live proof's offline verifier (a plain Node script beside the other repo scripts), pinned here. */
interface VerifyResult {
  readonly verdict: "PASS" | "FAIL";
  readonly checks: ReadonlyArray<{ readonly name: string; readonly ok: boolean }>;
}
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { verifyTx } = require("../../scripts/jx2VerifyTx") as { verifyTx: (input: Record<string, string | undefined>) => Promise<VerifyResult> };

const sha = (bytes: Uint8Array | string) => createHash("sha256").update(bytes).digest();
const hex = (bytes: Uint8Array) => Buffer.from(bytes).toString("hex");
const HALF_N = SECP256K1_N / BigInt(2);

/* ------------------------------------------------------------------ */
/* The disposable key and the fake KMS                                  */
/* ------------------------------------------------------------------ */

/* `elliptic` is @cosmjs/crypto's own secp256k1 dependency (no @types in this tree): only the calls used here are typed. */
interface EllipticSignature {
  readonly r: { toString(base: 16): string };
  readonly s: { toString(base: 16): string };
  toDER(): number[];
}
interface EllipticKey {
  sign(message: Buffer, options: { canonical?: boolean; pers?: Buffer }): EllipticSignature;
  getPublic(compact: boolean, encoding: "array"): number[];
}
interface EllipticCurve {
  keyFromPrivate(secret: Buffer): EllipticKey;
  genKeyPair(): EllipticKey;
}
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { ec: EC } = require("elliptic") as { ec: new (curve: string) => EllipticCurve };
const secp = new EC("secp256k1");
const KEY_ARN = "arn:aws:kms:us-east-1:000000000000:key/00000000-0000-4000-8000-0000000000aa";

interface FakeKms extends KmsClient {
  readonly asked: Buffer[];
  readonly answered: { readonly der: Buffer; readonly highS: boolean }[];
  readonly spki: Buffer;
  readonly publicKeyObject: KeyObject;
}

/** A secp256k1 key made by OpenSSL, held only in memory; KMS's two calls over it. */
function disposableKms(): FakeKms {
  const { privateKey, publicKey } = generateKeyPairSync("ec", { namedCurve: "secp256k1" });
  const jwk = privateKey.export({ format: "jwk" }) as { d: string };
  const key = secp.keyFromPrivate(Buffer.from(jwk.d, "base64url"));
  const spki = publicKey.export({ type: "spki", format: "der" }) as Buffer;
  const asked: Buffer[] = [];
  const answered: { der: Buffer; highS: boolean }[] = [];
  let calls = 0;
  return {
    asked,
    answered,
    spki,
    publicKeyObject: createPublicKey({ key: spki, format: "der", type: "spki" }),
    async getPublicKey(keyRef) {
      expect(keyRef).toBe(KEY_ARN);
      return Uint8Array.from(spki);
    },
    async signDigest(keyRef, digest) {
      expect(keyRef).toBe(KEY_ARN);
      expect(digest.length).toBe(32);
      asked.push(Buffer.from(digest));
      calls += 1;
      const signature = key.sign(Buffer.from(digest), { canonical: false, pers: randomBytes(32) });
      let s = BigInt(`0x${signature.s.toString(16)}`);
      if (s <= HALF_N && calls % 2 === 0) s = SECP256K1_N - s; // the high-s twin: still a valid ECDSA signature
      const der = derOf(BigInt(`0x${signature.r.toString(16)}`), s);
      answered.push({ der, highS: s > HALF_N });
      return Uint8Array.from(der);
    },
  };
}

/** Minimal DER `ECDSA-Sig-Value` (what KMS answers). */
function derOf(r: bigint, s: bigint): Buffer {
  const int = (value: bigint) => {
    let body = bigIntTo32(value);
    while (body.length > 1 && body[0] === 0 && !(body[1] & 0x80)) body = body.subarray(1);
    if (body[0] & 0x80) body = Buffer.concat([Buffer.from([0]), body]);
    return Buffer.concat([Buffer.from([0x02, body.length]), body]);
  };
  const seq = Buffer.concat([int(r), int(s)]);
  return Buffer.concat([Buffer.from([0x30, seq.length]), seq]);
}

/* ------------------------------------------------------------------ */
/* Representative escrow intents: every route the relayer signs         */
/* ------------------------------------------------------------------ */

type Vector = (typeof vectors.payload_vectors)[number];
const settleVector = vectors.payload_vectors.find((v) => v.usage === "Settle" && v.payload.seat_count === 6) as Vector;
const checkpointVector = vectors.payload_vectors.find((v) => v.usage === "Checkpoint") as Vector;
/** Test-only secrets (a settlement key and the seats' consent keys) for representative, VALID inner signatures. */
const SETTLEMENT_SECRET = sha("jx2a/settlement");
const seatSecret = (seat: number) => sha(`jx2a/consent/${seat}`);
const CHAIN_GAME_ID = "18446744073709551615"; // u64::MAX: the JSON integer path at its edge

const POLICY: GasPolicy = { ...DEFAULT_GAS_POLICY, feeDenom: "ujunox" };
/** L6-12D's `perTransactionFeeCap` (server `aws/deploy/junoChain.ts`), restated with the same `ceilDiv`: that module pulls the
 *  server's configuration types, which this tree's es5 typecheck does not compile. The server-side JX-2A suite asserts the
 *  two are the same function of the policy. */
const perTransactionFeeCap = (gas: GasPolicy): bigint => {
  const derived = ceilDiv(gas.maxGas * gas.gasPriceNum, gas.gasPriceDen);
  return gas.maxFee < derived ? gas.maxFee : derived;
};

interface Route {
  readonly name: string;
  readonly msgJson: string;
  /** A representative node answer for the simulation (the floor, the middle, and the exact max_gas boundary). */
  readonly simulatedGas: string;
}

function routes(): Route[] {
  const settleSig = signDigest(SETTLEMENT_SECRET, Buffer.from(settleVector.settle_digest, "hex")).toString("hex");
  const checkpointSig = signDigest(SETTLEMENT_SECRET, Buffer.from(checkpointVector.settle_digest, "hex")).toString("hex");
  const consentDigest = consentDigestV1(settleVector.payload.domain, BigInt(settleVector.payload.seq), settleVector.settle_digest);
  expect(consentDigest).toBe(settleVector.consent_digest);
  const consentSig = signDigest(seatSecret(2), Buffer.from(consentDigest, "hex")).toString("hex");
  const annulDigest = annulDigestV1(checkpointVector.payload.domain, BigInt(checkpointVector.payload.seq));
  const annulConsents = Array.from({ length: checkpointVector.payload.seat_count }, (_, seat) => ({ seat_index: seat, signature: signDigest(seatSecret(seat), Buffer.from(annulDigest, "hex")).toString("hex") }));
  return [
    { name: "Start", msgJson: RELAYER_EXECUTE.start(CHAIN_GAME_ID, sha("jx2a/roster").toString("hex")), simulatedGas: "151234" },
    { name: "Checkpoint", msgJson: RELAYER_EXECUTE.checkpoint("42", checkpointVector.payload as never, checkpointSig), simulatedGas: "420017" },
    { name: "Consent", msgJson: RELAYER_EXECUTE.consent("42", 2, consentSig), simulatedGas: "200001" },
    // The exact max_gas boundary: ceil(1,153,846 x 13/10) = 1,500,000 = max_gas, so the fee is the per-transaction cap.
    { name: "Settle", msgJson: RELAYER_EXECUTE.settle("42", settleVector.payload as never, settleSig), simulatedGas: "1153846" },
    // Below the floor: the gas limit is min_gas (80,000).
    { name: "Finalize", msgJson: RELAYER_EXECUTE.finalize("42"), simulatedGas: "61000" },
    { name: "AnnulByConsent", msgJson: RELAYER_EXECUTE.annulByConsent("42", annulConsents), simulatedGas: "333333" },
  ];
}

/* ------------------------------------------------------------------ */
/* The suite                                                            */
/* ------------------------------------------------------------------ */

describe("JX-2A: KMS -> Cosmos signing pipeline, every relayer route, byte parity with CosmJS (local disposable key)", () => {
  const CHAIN_ID = "uni-7";
  const ACCOUNT_NUMBER = "48213";
  const CONTRACT = toBech32("juno", sha("jx2a/contract")); // a 32-byte contract address, as wasmd's are

  let kms: FakeKms;
  let signer: Awaited<ReturnType<typeof openKmsDigestSigner>>;
  let publicKey: Buffer;
  let sender: string;

  beforeAll(async () => {
    kms = disposableKms();
    signer = await openKmsDigestSigner(kms, KEY_ARN);
    publicKey = signer.publicKey;
    sender = addressOfPublicKey(publicKey, "juno");
  });

  it("GetPublicKey: OpenSSL's SPKI -> the signer's compressed key = elliptic's = CosmJS's; the address is CosmJS's", async () => {
    const point = createPublicKey({ key: kms.spki, format: "der", type: "spki" }).export({ format: "jwk" }) as { x: string; y: string };
    const x = Buffer.from(point.x, "base64url");
    const y = Buffer.from(point.y, "base64url");
    const uncompressed = Buffer.concat([Buffer.from([4]), x, y]);
    expect(hex(publicKey)).toBe(hex(Secp256k1.compressPubkey(uncompressed)));
    expect(sender).toBe(toBech32("juno", rawSecp256k1PubkeyToRawAddress(publicKey)));
    expect(signer.kind).toBe("kms");
    expect(signer.label).toBe(KEY_ARN);
  });

  it.each(routes().map((route, i) => [i, route.name, route] as const))("route %i (%s): intent -> SignDoc -> digest -> KMS DER -> low-s r||s -> TxRaw, independently decoded and verified", async (_i, _name, route) => {
    const sequence = String(7 + _i);
    const timeoutHeight = String(5_000_000 + _i * 61);

    /* 1. The gas policy's decision (the relayer's own: decideGas over the node's simulated gas). */
    const gas = decideGas(route.simulatedGas, POLICY);
    if (!gas.ok) throw new Error(gas.reason);
    expect(gas.fee <= perTransactionFeeCap(POLICY)).toBe(true);
    expect(gas.gasLimit <= POLICY.maxGas).toBe(true);
    expect(gas.gasLimit >= POLICY.minGas).toBe(true);

    /* 2-4. Build exactly as `advance` does: the same base for the simulation probe and the signed transaction. */
    const base = { chainId: CHAIN_ID, accountNumber: ACCOUNT_NUMBER, sequence, sender, contract: CONTRACT, msgJson: route.msgJson, publicKey, timeoutHeight, memo: "" };
    const probe = prepareExecuteTx({ ...base, gasLimit: POLICY.maxGas.toString(), fee: { denom: POLICY.feeDenom, amount: "0" } });
    const prepared = prepareExecuteTx({ ...base, gasLimit: gas.gasLimit.toString(), fee: { denom: POLICY.feeDenom, amount: gas.fee.toString() } });

    /* CosmJS's own construction of the same transaction. */
    const msgBytes = Buffer.from(route.msgJson, "utf8");
    const theirMsg = MsgExecuteContract.encode(MsgExecuteContract.fromPartial({ sender, contract: CONTRACT, msg: msgBytes, funds: [] })).finish();
    const theirBody = TxBody.encode(TxBody.fromPartial({ messages: [{ typeUrl: MSG_EXECUTE_CONTRACT_TYPE_URL, value: theirMsg }], memo: "", timeoutHeight: BigInt(timeoutHeight) })).finish();
    const theirAuth = AuthInfo.encode(
      AuthInfo.fromPartial({
        signerInfos: [SignerInfo.fromPartial({ publicKey: encodePubkey(encodeSecp256k1Pubkey(publicKey)), modeInfo: { single: { mode: SignMode.SIGN_MODE_DIRECT } }, sequence: BigInt(sequence) })],
        fee: Fee.fromPartial({ amount: [{ denom: "ujunox", amount: gas.fee.toString() }], gasLimit: gas.gasLimit }),
      }),
    ).finish();
    const theirSignBytes = makeSignBytes(makeSignDoc(theirBody, theirAuth, CHAIN_ID, Number(ACCOUNT_NUMBER)));

    expect(hex(prepared.bodyBytes)).toBe(hex(theirBody));
    expect(hex(prepared.authInfoBytes)).toBe(hex(theirAuth));
    expect(hex(prepared.signDoc)).toBe(hex(theirSignBytes));
    expect(hex(prepared.digest)).toBe(hex(sha256(theirSignBytes)));
    /* The probe and the signed transaction share the body: only the fee and the gas limit differ. */
    expect(hex(probe.bodyBytes)).toBe(hex(prepared.bodyBytes));

    /* 5-6. KMS signs THE DIGEST (exactly those 32 bytes); the signer parses DER, normalises low-s and verifies. */
    const asked = kms.asked.length;
    const signature = await signer.sign(prepared.digest);
    expect(kms.asked.length).toBe(asked + 1);
    expect(hex(kms.asked[asked])).toBe(hex(sha256(theirSignBytes)));
    expect(signature.length).toBe(64);
    expect(isLowS(signature)).toBe(true);
    const der = kms.answered[kms.answered.length - 1];
    /* r is KMS's r; s is KMS's s or n - s (the low-s twin). */
    const kmsSig = Secp256k1Signature.fromDer(der.der);
    expect(hex(signature.subarray(0, 32))).toBe(hex(kmsSig.r(32)));
    const kmsS = bytesToBigInt(kmsSig.s(32));
    expect(bytesToBigInt(signature.subarray(32))).toBe(der.highS ? SECP256K1_N - kmsS : kmsS);

    /* 7. TxRaw: ours = CosmJS's with the same signature; the id is SHA-256 of the bytes. */
    const signed = assembleTx(prepared, signature);
    const theirRaw = TxRaw.encode(TxRaw.fromPartial({ bodyBytes: theirBody, authInfoBytes: theirAuth, signatures: [signature] })).finish();
    expect(hex(signed.txBytes)).toBe(hex(theirRaw));
    expect(signed.txHash).toBe(hex(sha256(theirRaw)).toUpperCase());
    expect(txHashOf(theirRaw)).toBe(signed.txHash);

    /* 8. Independently decoded, as a node would: every field the chain reads. */
    const raw = TxRaw.decode(signed.txBytes);
    expect(raw.signatures).toHaveLength(1);
    expect(hex(raw.signatures[0])).toBe(hex(signature));
    const body = TxBody.decode(raw.bodyBytes);
    expect(body.messages).toHaveLength(1);
    expect(body.messages[0].typeUrl).toBe("/cosmwasm.wasm.v1.MsgExecuteContract");
    expect(body.memo).toBe("");
    expect(body.timeoutHeight).toBe(BigInt(timeoutHeight));
    expect(body.extensionOptions).toHaveLength(0);
    expect(body.nonCriticalExtensionOptions).toHaveLength(0);
    const msg = MsgExecuteContract.decode(body.messages[0].value);
    expect(msg.sender).toBe(sender);
    expect(msg.contract).toBe(CONTRACT);
    expect(msg.funds).toHaveLength(0); // every relayer route is non-payable
    expect(Buffer.from(msg.msg).toString("utf8")).toBe(route.msgJson);
    expect(Object.keys(JSON.parse(route.msgJson))).toHaveLength(1);
    const auth = AuthInfo.decode(raw.authInfoBytes);
    expect(auth.signerInfos).toHaveLength(1);
    const info = auth.signerInfos[0];
    expect(info.publicKey?.typeUrl).toBe("/cosmos.crypto.secp256k1.PubKey");
    expect(hex(PubKey.decode(info.publicKey!.value).key)).toBe(hex(publicKey));
    expect(info.modeInfo?.single?.mode).toBe(SignMode.SIGN_MODE_DIRECT);
    expect(info.sequence).toBe(BigInt(sequence));
    expect(auth.fee?.amount).toEqual([{ denom: "ujunox", amount: gas.fee.toString() }]);
    expect(auth.fee?.gasLimit).toBe(gas.gasLimit);
    expect(auth.fee?.payer).toBe("");
    expect(auth.fee?.granter).toBe("");

    /* The chain's own check: rebuild the sign bytes FROM THE DECODED TxRaw, then verify -- CosmJS and OpenSSL. */
    const chainSignBytes = makeSignBytes(makeSignDoc(raw.bodyBytes, raw.authInfoBytes, CHAIN_ID, Number(ACCOUNT_NUMBER)));
    expect(hex(chainSignBytes)).toBe(hex(prepared.signDoc));
    expect(await Secp256k1.verifySignature(Secp256k1Signature.fromFixedLength(signature), sha256(chainSignBytes), publicKey)).toBe(true);
    expect(opensslVerify("sha256", chainSignBytes, { key: kms.publicKeyObject, dsaEncoding: "ieee-p1363" }, signature)).toBe(true);
    /* ...and it is THIS transaction's signature only: another chain id or account number does not verify. */
    expect(opensslVerify("sha256", makeSignBytes(makeSignDoc(raw.bodyBytes, raw.authInfoBytes, "juno-1", Number(ACCOUNT_NUMBER))), { key: kms.publicKeyObject, dsaEncoding: "ieee-p1363" }, signature)).toBe(false);
    expect(opensslVerify("sha256", makeSignBytes(makeSignDoc(raw.bodyBytes, raw.authInfoBytes, CHAIN_ID, Number(ACCOUNT_NUMBER) + 1)), { key: kms.publicKeyObject, dsaEncoding: "ieee-p1363" }, signature)).toBe(false);

    /* The handoff's offline verifier (scripts/jx2VerifyTx.js) passes the same bytes, and fails them under another account. */
    const verified = await verifyTx({ txBase64: signed.txBytes.toString("base64"), chainId: CHAIN_ID, accountNumber: ACCOUNT_NUMBER, pubkey: hex(publicKey), hash: signed.txHash, contract: CONTRACT, sequence, fee: gas.fee.toString(), denom: "ujunox", gasLimit: gas.gasLimit.toString() });
    expect(verified.checks.filter((c) => !c.ok)).toEqual([]);
    expect(verified.verdict).toBe("PASS");
    expect((await verifyTx({ txBase64: signed.txBytes.toString("base64"), chainId: CHAIN_ID, accountNumber: String(Number(ACCOUNT_NUMBER) + 1), pubkey: hex(publicKey) })).verdict).toBe("FAIL");

    /* The simulation form decodes as one empty signature over the probe's bytes (never signed, never broadcast). */
    const sim = TxRaw.decode(simulationTx(probe));
    expect(sim.signatures).toHaveLength(1);
    expect(sim.signatures[0]).toHaveLength(0);
    expect(AuthInfo.decode(sim.authInfoBytes).fee?.gasLimit).toBe(POLICY.maxGas);

    /* Non-determinism: a second KMS signature over the same digest may differ; the sign bytes cannot, and both verify. */
    const again = assembleTx(prepared, await signer.sign(prepared.digest));
    const rawAgain = TxRaw.decode(again.txBytes);
    expect(hex(rawAgain.bodyBytes)).toBe(hex(raw.bodyBytes));
    expect(hex(rawAgain.authInfoBytes)).toBe(hex(raw.authInfoBytes));
    expect(opensslVerify("sha256", chainSignBytes, { key: kms.publicKeyObject, dsaEncoding: "ieee-p1363" }, rawAgain.signatures[0])).toBe(true);
    if (hex(rawAgain.signatures[0]) !== hex(raw.signatures[0])) expect(again.txHash).not.toBe(signed.txHash);
  });

  it("the run exercised both KMS answer shapes (high-s normalised, low-s kept) and never-deterministic signatures", async () => {
    const digest = sha("jx2a/non-determinism");
    const seen = new Set<string>();
    for (let n = 0; n < 8; n += 1) seen.add(hex(await signer.sign(digest)));
    expect(seen.size).toBeGreaterThan(1);
    expect(kms.answered.some((answer) => answer.highS)).toBe(true);
    expect(kms.answered.some((answer) => !answer.highS)).toBe(true);
  });

  it("fail closed: a KMS answer for ANOTHER key, a malformed DER, and a high-s DER that is not for this digest are never used", async () => {
    const other = secp.genKeyPair();
    const liar: KmsClient = {
      getPublicKey: kms.getPublicKey,
      async signDigest(_ref, digest) {
        const sig = other.sign(Buffer.from(digest), { canonical: true });
        return Uint8Array.from(sig.toDER());
      },
    };
    const lying = await openKmsDigestSigner(liar, KEY_ARN);
    await expect(lying.sign(sha("x"))).rejects.toMatchObject({ code: "verify-failed" });

    const garbled: KmsClient = { getPublicKey: kms.getPublicKey, signDigest: async () => Uint8Array.from([0x30, 0x02, 0x02, 0x00]) };
    await expect((await openKmsDigestSigner(garbled, KEY_ARN)).sign(sha("y"))).rejects.toBeInstanceOf(SignerError);

    const wrongDigest: KmsClient = { getPublicKey: kms.getPublicKey, signDigest: async (ref, digest) => kms.signDigest(ref, sha(Buffer.from(digest))) };
    await expect((await openKmsDigestSigner(wrongDigest, KEY_ARN)).sign(sha("z"))).rejects.toMatchObject({ code: "verify-failed" });

    /* A non-secp256k1 key (P-256) is refused at open. */
    const p256 = generateKeyPairSync("ec", { namedCurve: "prime256v1" }).publicKey.export({ type: "spki", format: "der" }) as Buffer;
    await expect(openKmsDigestSigner({ getPublicKey: async () => Uint8Array.from(p256), signDigest: kms.signDigest }, KEY_ARN)).rejects.toMatchObject({ code: "config" });
  });

  it("gas boundary: one more simulated gas unit than the max_gas boundary is refused (no transaction); the cap equals the planning cap", () => {
    expect(decideGas("1153846", POLICY)).toEqual({ ok: true, gasLimit: BigInt(1_500_000), fee: BigInt(112_500) });
    expect(perTransactionFeeCap(POLICY)).toBe(BigInt(112_500));
    expect(decideGas("1153847", POLICY).ok).toBe(false);
    expect(decideGas("0", POLICY).ok).toBe(false);
    /* The decoded fee of every transaction is <= the cap whatever the node answers (exhaustive over the accepted range's edges). */
    for (const used of ["1", "61538", "61539", "80000", "1000000", "1153845", "1153846"]) {
      const decision = decideGas(used, POLICY);
      if (!decision.ok) throw new Error(decision.reason);
      expect(decision.fee).toBe((decision.gasLimit * BigInt(75) + BigInt(999)) / BigInt(1000));
      expect(decision.fee <= perTransactionFeeCap(POLICY)).toBe(true);
    }
  });

  it("the development path and the KMS path produce the same SignDoc for the same key (only the signature source differs)", async () => {
    /* publicKeyOf over a test secret equals the SPKI path for the same scalar; the KMS signer adds nothing to the bytes signed. */
    const secret = sha("jx2a/same-key");
    const kp = secp.keyFromPrivate(secret);
    const uncompressed = Buffer.from(kp.getPublic(false, "array"));
    const spki = Buffer.concat([Buffer.from("3056301006072a8648ce3d020106052b8104000a034200", "hex"), uncompressed]);
    const viaKms = await openKmsDigestSigner({ getPublicKey: async () => Uint8Array.from(spki), signDigest: async (_r, d) => Uint8Array.from(kp.sign(Buffer.from(d), { pers: randomBytes(32) }).toDER()) }, KEY_ARN);
    expect(hex(viaKms.publicKey)).toBe(hex(publicKeyOf(secret)));
    const prepared = prepareExecuteTx({ chainId: "uni-7", accountNumber: "1", sequence: "0", sender: addressOfPublicKey(viaKms.publicKey, "juno"), contract: CONTRACT, msgJson: RELAYER_EXECUTE.finalize("1"), publicKey: viaKms.publicKey, gasLimit: "80000", fee: { denom: "ujunox", amount: "6000" }, timeoutHeight: "100", memo: "" });
    const viaDev = signDigest(secret, prepared.digest);
    const viaKmsSig = await viaKms.sign(prepared.digest);
    const raw1 = TxRaw.decode(assembleTx(prepared, viaDev).txBytes);
    const raw2 = TxRaw.decode(assembleTx(prepared, viaKmsSig).txBytes);
    expect(hex(raw1.bodyBytes)).toBe(hex(raw2.bodyBytes));
    expect(hex(raw1.authInfoBytes)).toBe(hex(raw2.authInfoBytes));
    expect(viaKmsSig).toHaveLength(64);
  });
});
