// frontend/src/utils/turnAuthority.ts
//
// Whether this actor may send this message right now.
//
// ==================================================================
//  DESIGN NOTE 1205: THE QUESTION THAT DEFEATED THE REDUCER TWICE
// ==================================================================
//
// #1174 AND #1182 BOTH DIED HERE. The first put `offTurnRefusal(state, msg, actor)` inside the reducer and
// broke ten tests across four suites -- including `replayAttribution`, #549's own divergence harness, whose
// whole subject is that the reducer must not read the seat cursor. The second compared a message's
// `protocol_id` against `active_corporation_index` and reached real players, producing three separate-looking
// reports that were one bug.
//
// THE REASON THEY FAILED IS NOT THE REASON IT LOOKED LIKE. Both notes conclude that a refusal may only compare
// values identical on every client BY CONSTRUCTION, and neither cursor was: two browsers whose market charts
// had drifted built different operating orders, so a refusal keyed on the queue made a board's CONTENTS depend
// on that disagreement.
//
// THAT OBJECTION DOES NOT SURVIVE A SERVER. It was never about the rule; it was about there being two
// judges. One writer cannot disagree with itself, so the thing #1174 could not do inside a replay is exactly
// what an authority is for. This module is therefore NOT the refusal those notes forbid -- it is the check
// they said belonged somewhere else, finally somewhere else.
//
// AND IT IS NOT A SECOND IMPLEMENTATION OF "WHOSE TURN IS IT". `actingAddress` in `gameState.ts` already
// answers all four cases and has for a long time: the mini-auction's own cursor (#544), the waterfall
// rotation, the Stock Round seat, and the Operating Round's PRESIDENT rather than any seat index (#411).
// What the reducer lacked was never the rule -- it was the auction atom, which `actingAddress` needs and
// `applyOneAction` was never passed. `RoomEngine` holds both. So this file resolves the actor, asks that
// function, and spends its length on the EXEMPTIONS, which is where the real complexity always was.
//
// THE EXEMPTIONS ARE THREE, NOT FOUR, and correcting that is worth recording. #1174's note lists four flows
// as "legitimately off-turn", and the fourth -- "a `SellStock` that does not advance the seat at all" -- is an
// observation about the CURSOR rather than about authority. A sale that leaves the seat where it is still
// happens on the seller's turn. The shell's own gate has exactly three exemptions
// (`isRemoteReplay`, `automatic`, `offTurn`) and no arm for `SellStock`, which settles it.
//
// A REFUSAL HERE REFUSES AN ACTION. On the client this rule greyed a button; here it rejects a request, so
// every exemption below is a case where a player would otherwise be locked out of a move the rules allow.

import type { GameStateResponse, WaterfallStateResponse } from "./gameState";
import { actingAddress } from "./gameState";
/* #1220: the SAME predicate the shell dispatches by (#546), not a second list. A copy here would drift the
   moment an eleventh message joined the family, and drift in this direction locks players out of moves. */
import { isSandboxOnlyMsg } from "./gameSetup";
import type { GameplayExecuteMsg } from "./sessionKey";
import { BO_PRIVATE_ID, BO_TICKER } from "./gameConstants";
import { DH_PRIVATE_ID } from "./dhPower";
import { effectiveActions, type RevertableAction } from "./logRevert";

export interface TurnAuthorityInput {
  state: GameStateResponse;
  /** #544: the mini-auction's cursor lives here, and it SUSPENDS the main rotation while a contest runs. */
  waterfall: WaterfallStateResponse | null;
  /** Who sent it. `null` is a legitimate state, not a missing one -- see the solo exemption below. */
  actor: string | null;
  msg: GameplayExecuteMsg;
  /** Generated by the server itself (#1203). The authority does not audit its own output. */
  derived?: boolean;
  /** #1249: the room's host, from the room document. `undefined` means the caller has no room document (a
   *  test, a CLI replay) and the host-only checks are skipped -- #232: absent is "not said", never "nobody". */
  host?: string | null;
  /** #1249: the log as it stands, for `RevertTo` -- the one message whose authority is about history rather
   *  than about the board. Same rule as `undoReachFor`; `undefined` skips it for the same reason as `host`. */
  log?: readonly RevertableAction[];
}

/** Why this actor may not send this message now, or `null` if they may. */
export function turnRefusal(input: TurnAuthorityInput): string | null {
  const { state, waterfall, actor, msg, derived = false } = input;

  /* ---- EXEMPTION 1: the game's own actions (#1203, and the shell's `automatic`) ----
     The server generated these in `RoomEngine.submit` after a player's move -- the forced withhold, the
     auto-skip, the turn that ended itself. Checking them would be the authority interrogating itself, and
     they are by definition not on anybody's turn: a corporation whose turn just ended is exactly who the
     `PassTurn` is for. */
  if (derived) return null;

  /* ---- EXEMPTION 2: solo play and attribution-less actions (#549b) ----
     A null actor is a POSITIVE STATE, not a missing field: `applyOneAction` resolves it to "the cursor" for
     solo play deliberately. Refusing here would make a single-player game unplayable, and there is nobody to
     take a turn from. */
  if (actor === null) return null;

  /* ---- EXEMPTION 3: consent answers on a two-party trade (#701) ----
     THE OWED ANSWER IS ALWAYS OFF-TURN, BY CONSTRUCTION. A corporation on its turn OFFERS; the private's
     owner or the selling president ANSWERS, and that player is by definition not the one operating. The
     shell marks these `offTurn: true` at all four dispatch sites for exactly this reason.
     ASKED AGAINST THE BOARD, NOT AGAINST A FLAG. #1198 put both offers on the state, so "is this actor the
     counterparty of an open offer" is a state read rather than something the sender asserts about itself --
     which matters when the sender is a network client rather than the shell's own code. */
  const consent = consentAnswerRefusal(state, actor, msg);
  if (consent !== "not-a-consent-answer") return consent;

  /* ==================================================================
      EXEMPTION 4 (#1220): THE MESSAGES THAT ARE NOT A SEAT'S TO SEND
     ==================================================================
     REPORTED, after four separate one-button fixes: "'Proceed to Stock Round 1' button doesn't work. It
     seems like we are iteratively needing to fix every single button and transition." And the server said
     `refused: p-qnvjx852 sent OpenStockRound — It is not your turn.`

     IT WAS ALWAYS ONE BUG. Exemption 1 above claims to cover "#1203, and the shell's `automatic`", and that
     conflation is the whole fault: `derived` is only what the SERVER generates. The shell's `automatic` flag
     covers a much larger family -- every message in `isSandboxOnlyMsg` is dispatched with it, at every one of
     its call sites -- and not one of them is derived. So the client let them through and the server refused
     them, one button at a time, in the order the playtest happened to reach them.

     THESE ARE NOT MOVES. `OpenStockRound` and `SetBoPar` close a phase; `PlaceHomeStation` places a token the
     rules place for you; `ExchangePrivate` is the M&H's own right, explicitly exercisable between other
     players' turns; `RevertTo` and `CloseRoom` are the room's, not a seat's. Asking "is it your turn" of a
     phase transition is a category error -- the transition belongs to the GAME, and the seat cursor at that
     moment usually points at somebody who has just finished.

     DECIDED FROM THE MESSAGE, NEVER FROM A FLAG, and that distinction is the reason this is safe. A client
     asserting `automatic: true` on the wire would be a client granting itself an exemption, which is exactly
     what #1207 keeps off the wire. `isSandboxOnlyMsg` is a property of the message the server can see for
     itself, and it is the SAME PREDICATE the shell uses (#546) rather than a second list that would drift
     from it -- #1184's shape, avoided by construction.

     THE CONSENT ANSWERS ARE IN THIS FAMILY TOO AND MUST NOT REACH HERE. Exemption 3 runs first and returns
     for all four negotiation messages, so their real owner checks stand. The order of these blocks is load-
     bearing; moving this one above it would hand every trade answer to anybody.

     WHAT #1220 LEFT UNGUARDED, in its own words: "any player in the room may send `OpenStockRound`,
     `SetBoPar`, `PlaceHomeStation`, `ExchangePrivate`, `RevertTo` or `CloseRoom` at any time ... a real gap
     and it is recorded in the migration plan as one." #1249 closes it -- see `roomMessageRefusal`. The
     exemption from the SEAT stands; what each message gets instead is its own owner. */
  if (isSandboxOnlyMsg(msg)) {
    return roomMessageRefusal(input, actor);
  }

  /* ---- THE RULE ITSELF ----
     One function, four cases, and the auction atom it always needed. */
  const acting = actingAddress(state, waterfall);

  /* AN UNRESOLVABLE CURSOR ALLOWS THE ACTION THROUGH, matching `dividendGate` and `trainPurchaseGate`
     exactly: "an unknown cursor is allowed through, deliberately ... refusing there would brick a board on
     the strength of a missing field rather than a broken rule". `actingAddress` returns `null` for an empty
     roster, an unseated president, or a corporation the queue cannot name -- none of which is evidence that
     THIS player is out of turn. */
  if (acting === null) return null;

  if (actor === acting) return null;

  return "It is not your turn.";
}

/* ==================================================================
    DESIGN NOTE 1249: EACH ROOM MESSAGE HAS AN OWNER, EVEN THOUGH NONE HAS A SEAT
   ==================================================================
   #1220 exempted the whole family from the seat and said so was a gap. It was, and the reason it was left
   open is worth restating: "the answers are per-message and mostly need the room document (who is host) or
   the reducer's own legality checks, neither of which belongs in a turn gate." Half of that is still true --
   the reducer's legality checks stay the reducer's -- and the other half is answered by two more inputs, the
   host and the log, both of which the server holds and hands over.

   THE RULES, ONE PER MESSAGE, and each is the question the SHELL already asks before it shows the button:
     SetupGame        the host starts the game (the Start button is the host's), on an undealt board.
     OpenStockRound   the auction must be over -- `auctionHandoffPending` in the shell: round is the auction
                      and the atom has no private left to sell. Anybody may press it, as anybody may in the
                      shell; the board decides whether it is true.
     SetBoPar         the B&O private's owner, and the message must name them (#549: the winner travels).
     PlaceHomeStation the corporation's president; a D&H placement additionally by the D&H's owner.
     ExchangePrivate  the private's owner, named in the message.
     RevertTo         `undoReachFor`'s rule, on the server's own log: the host reverts anything; anybody else
                      only their own last non-derived action, and only when it is the last one standing.
     CloseRoom        at GameEnd. A close that lost the race is still allowed through so #899's silence holds
                      (the reducer no-ops it); what is refused is closing a game that is not over.

   REFUSED BY THE OWNER, NEVER BY LEGALITY. Whether the B&O CAN be parred (`boPresidencyRefusal`), whether a
   token IS owed, whether an exchange is legal -- those are the reducer's, and a refusal here that duplicated
   them would be #1184's shape. This asks only "is this yours to send".

   `undefined` HOST OR LOG SKIPS THAT CHECK, deliberately. The replay harness and the CLI run this without a
   room document; refusing there would be a gate judging on a field nobody gave it. On the server both are
   always supplied (`RoomSession.submit`). */
function roomMessageRefusal(input: TurnAuthorityInput, actor: string): string | null {
  const { state, waterfall, msg, host, log } = input;

  if ("SetupGame" in msg) {
    /* #538's rule read from the other side -- "a room's roster is not the fixture, corrected; it is nothing,
       until the log says otherwise" -- so a non-empty roster IS the record that the deal has happened. */
    if (state.player_addresses.length > 0) return "This game has already been dealt.";
    if (host !== undefined && host !== null && actor !== host) return "Only the host can start the game.";
    return null;
  }

  if ("OpenStockRound" in msg) {
    if (state.current_round_type !== "WaterfallAuction") return "The Stock Round is already open.";
    const unsold = waterfall?.privates.length ?? 0;
    if (unsold > 0) {
      return `The auction is not over yet — ${unsold} private ${unsold === 1 ? "company is" : "companies are"} still for sale.`;
    }
    return null;
  }

  if ("SetBoPar" in msg) {
    const { player } = msg.SetBoPar as { player: string };
    const owner = state.private_companies.find((entry) => entry.private_id === BO_PRIVATE_ID)?.owner ?? null;
    if (actor !== player || (owner !== null && owner !== actor)) {
      return `Only the ${BO_TICKER} private's owner pars the ${BO_TICKER}.`;
    }
    return null;
  }

  if ("PlaceHomeStation" in msg) {
    const { company_id, kind } = msg.PlaceHomeStation as { company_id: number; kind?: string };
    const company = state.public_companies.find((entry) => entry.company_id === company_id);
    if (!company) return "That corporation is not in this game.";
    if (company.president !== actor) return `Only ${company.ticker}'s president places its station.`;
    if (kind === "dh") {
      const dh = state.private_companies.find((entry) => entry.private_id === DH_PRIVATE_ID);
      if (dh && dh.owner !== actor) return "Only the Delaware & Hudson's owner can use its free station.";
    }
    return null;
  }

  if ("ExchangePrivate" in msg) {
    const { player, private_id } = msg.ExchangePrivate as { player: string; private_id: number };
    const priv = state.private_companies.find((entry) => entry.private_id === private_id);
    if (actor !== player || (priv !== undefined && priv.owner !== actor)) {
      return `Only the ${priv?.name ?? "private company"}'s owner can exchange it.`;
    }
    return null;
  }

  if ("RevertTo" in msg) {
    if (log === undefined) return null;
    if (host !== undefined && host !== null && actor === host) return null;
    const { index } = msg.RevertTo as { index: number };
    const live = effectiveActions(log);
    const target = live.find((entry) => entry.index === index) ?? null;
    if (target === null) return "There is nothing at that point in the log to undo.";
    const last = [...live].reverse().find((entry) => entry.derived !== true) ?? null;
    if (last === null || last.index !== target.index || target.actor !== actor) {
      return "Other players have acted since your last move. Only the host can undo past somebody else's turn.";
    }
    return null;
  }

  if ("CloseRoom" in msg) {
    return state.current_round_type === "GameEnd" ? null : "The game is not over yet.";
  }

  /* Design note #1323: THE LICENCE IS THE OPERATING PRESIDENT'S TO BUY. It is sandbox-only (the chain has
     never heard of it) so it lands here rather than at the seat cursor, and its owner is the president of the
     corporation named -- the same test `PlaceHomeStation` makes. Whether that corporation is the one
     operating, at the Lay Track step, with the money, is `kanawhaLicenseRefusal`'s question and the arm's. */
  if ("BuyKanawhaLicense" in msg) {
    const { protocol_id } = msg.BuyKanawhaLicense as { protocol_id: number };
    const company = state.public_companies.find((entry) => entry.company_id === protocol_id);
    if (!company) return "That corporation is not in this game.";
    if (company.president !== actor) return `Only ${company.ticker}'s president buys its Kanawha Licence.`;
    return null;
  }

  return null;
}

/** `"not-a-consent-answer"` when the message is not one; otherwise a refusal or `null`.
 *
 *  A THREE-VALUED ANSWER ON PURPOSE. Folding "this is not a consent answer" into `null` would exempt every
 *  message that happens not to match, which is the whole gate. #232's rule about absence, applied to a
 *  branch rather than to a field. */
function consentAnswerRefusal(
  state: GameStateResponse,
  actor: string,
  msg: GameplayExecuteMsg,
): string | null | "not-a-consent-answer" {
  if ("AnswerPrivatePurchase" in msg) {
    const offer = state.private_purchase_offer ?? null;
    /* #662: answering an offer that is no longer there is not an error -- the first answer settles it and
       the second finds nothing. The reducer's arm returns the state unchanged; refusing here would turn a
       harmless duplicate into an error message on somebody's screen. */
    if (!offer) return null;
    return offer.owner === actor
      ? null
      : "Only the private company's owner can answer that offer.";
  }

  if ("AnswerTrainPurchase" in msg) {
    const offer = state.train_purchase_offer ?? null;
    if (!offer) return null;
    /* THE SELLER'S PRESIDENT ANSWERS, and it is the BUYER who is on turn -- #701 states the direction
       explicitly, and getting it backwards would refuse every train trade in the game. */
    return offer.seller_president === actor
      ? null
      : "Only the selling corporation's president can answer that offer.";
  }

  return "not-a-consent-answer";
}
