// frontend/src/utils/turnAuthority.ts
//
// Whether this actor may send this message right now.
//
// ==================================================================
//  DESIGN NOTE 1205: THE QUESTION THAT DEFEATED THE REDUCER TWICE
// ==================================================================
//
// #1174 AND #1182 BOTH DIED HERE. The first put `offTurnRefusal(state, msg, actor)` inside the reducer and
// broke ten tests across four suites -- including `replayAttribution`, #549's own divergence harness, whose
// whole subject is that the reducer must not read the seat cursor. The second compared a message's
// `protocol_id` against `active_corporation_index` and reached real players, producing three separate-looking
// reports that were one bug.
//
// THE REASON THEY FAILED IS NOT THE REASON IT LOOKED LIKE. Both notes conclude that a refusal may only compare
// values identical on every client BY CONSTRUCTION, and neither cursor was: two browsers whose market charts
// had drifted built different operating orders, so a refusal keyed on the queue made a board's CONTENTS depend
// on that disagreement.
//
// THAT OBJECTION DOES NOT SURVIVE A SERVER. It was never about the rule; it was about there being two
// judges. One writer cannot disagree with itself, so the thing #1174 could not do inside a replay is exactly
// what an authority is for. This module is therefore NOT the refusal those notes forbid -- it is the check
// they said belonged somewhere else, finally somewhere else.
//
// AND IT IS NOT A SECOND IMPLEMENTATION OF "WHOSE TURN IS IT". `actingAddress` in `gameState.ts` already
// answers all four cases and has for a long time: the mini-auction's own cursor (#544), the waterfall
// rotation, the Stock Round seat, and the Operating Round's PRESIDENT rather than any seat index (#411).
// What the reducer lacked was never the rule -- it was the auction atom, which `actingAddress` needs and
// `applyOneAction` was never passed. `RoomEngine` holds both. So this file resolves the actor, asks that
// function, and spends its length on the EXEMPTIONS, which is where the real complexity always was.
//
// THE EXEMPTIONS ARE THREE, NOT FOUR, and correcting that is worth recording. #1174's note lists four flows
// as "legitimately off-turn", and the fourth -- "a `SellStock` that does not advance the seat at all" -- is an
// observation about the CURSOR rather than about authority. A sale that leaves the seat where it is still
// happens on the seller's turn. The shell's own gate has exactly three exemptions
// (`isRemoteReplay`, `automatic`, `offTurn`) and no arm for `SellStock`, which settles it.
//
// A REFUSAL HERE REFUSES AN ACTION. On the client this rule greyed a button; here it rejects a request, so
// every exemption below is a case where a player would otherwise be locked out of a move the rules allow.

import type { GameStateResponse, WaterfallStateResponse } from "./gameState";
import { actingAddress } from "./gameState";
import type { GameplayExecuteMsg } from "./sessionKey";

export interface TurnAuthorityInput {
  state: GameStateResponse;
  /** #544: the mini-auction's cursor lives here, and it SUSPENDS the main rotation while a contest runs. */
  waterfall: WaterfallStateResponse | null;
  /** Who sent it. `null` is a legitimate state, not a missing one -- see the solo exemption below. */
  actor: string | null;
  msg: GameplayExecuteMsg;
  /** Generated by the server itself (#1203). The authority does not audit its own output. */
  derived?: boolean;
}

/** Why this actor may not send this message now, or `null` if they may. */
export function turnRefusal(input: TurnAuthorityInput): string | null {
  const { state, waterfall, actor, msg, derived = false } = input;

  /* ---- EXEMPTION 1: the game's own actions (#1203, and the shell's `automatic`) ----
     The server generated these in `RoomEngine.submit` after a player's move -- the forced withhold, the
     auto-skip, the turn that ended itself. Checking them would be the authority interrogating itself, and
     they are by definition not on anybody's turn: a corporation whose turn just ended is exactly who the
     `PassTurn` is for. */
  if (derived) return null;

  /* ---- EXEMPTION 2: solo play and attribution-less actions (#549b) ----
     A null actor is a POSITIVE STATE, not a missing field: `applyOneAction` resolves it to "the cursor" for
     solo play deliberately. Refusing here would make a single-player game unplayable, and there is nobody to
     take a turn from. */
  if (actor === null) return null;

  /* ---- EXEMPTION 3: consent answers on a two-party trade (#701) ----
     THE OWED ANSWER IS ALWAYS OFF-TURN, BY CONSTRUCTION. A corporation on its turn OFFERS; the private's
     owner or the selling president ANSWERS, and that player is by definition not the one operating. The
     shell marks these `offTurn: true` at all four dispatch sites for exactly this reason.
     ASKED AGAINST THE BOARD, NOT AGAINST A FLAG. #1198 put both offers on the state, so "is this actor the
     counterparty of an open offer" is a state read rather than something the sender asserts about itself --
     which matters when the sender is a network client rather than the shell's own code. */
  const consent = consentAnswerRefusal(state, actor, msg);
  if (consent !== "not-a-consent-answer") return consent;

  /* ---- THE RULE ITSELF ----
     One function, four cases, and the auction atom it always needed. */
  const acting = actingAddress(state, waterfall);

  /* AN UNRESOLVABLE CURSOR ALLOWS THE ACTION THROUGH, matching `dividendGate` and `trainPurchaseGate`
     exactly: "an unknown cursor is allowed through, deliberately ... refusing there would brick a board on
     the strength of a missing field rather than a broken rule". `actingAddress` returns `null` for an empty
     roster, an unseated president, or a corporation the queue cannot name -- none of which is evidence that
     THIS player is out of turn. */
  if (acting === null) return null;

  if (actor === acting) return null;

  return "It is not your turn.";
}

/** `"not-a-consent-answer"` when the message is not one; otherwise a refusal or `null`.
 *
 *  A THREE-VALUED ANSWER ON PURPOSE. Folding "this is not a consent answer" into `null` would exempt every
 *  message that happens not to match, which is the whole gate. #232's rule about absence, applied to a
 *  branch rather than to a field. */
function consentAnswerRefusal(
  state: GameStateResponse,
  actor: string,
  msg: GameplayExecuteMsg,
): string | null | "not-a-consent-answer" {
  if ("AnswerPrivatePurchase" in msg) {
    const offer = state.private_purchase_offer ?? null;
    /* #662: answering an offer that is no longer there is not an error -- the first answer settles it and
       the second finds nothing. The reducer's arm returns the state unchanged; refusing here would turn a
       harmless duplicate into an error message on somebody's screen. */
    if (!offer) return null;
    return offer.owner === actor
      ? null
      : "Only the private company's owner can answer that offer.";
  }

  if ("AnswerTrainPurchase" in msg) {
    const offer = state.train_purchase_offer ?? null;
    if (!offer) return null;
    /* THE SELLER'S PRESIDENT ANSWERS, and it is the BUYER who is on turn -- #701 states the direction
       explicitly, and getting it backwards would refuse every train trade in the game. */
    return offer.seller_president === actor
      ? null
      : "Only the selling corporation's president can answer that offer.";
  }

  return "not-a-consent-answer";
}
